serverconfig:
  port: "4949"

apps:
  - appid: hyperhdr
    filepath: "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\HyperHDR\\HyperHDR.lnk"
    waittime: 2
  - appid: notepad++
    filepath: "C:\\Program Files\\Notepad++\\notepad++.exe"
    waittime: 1
